name: ${project.name}
main: net.civex4.nobility.Nobility
version: ${project.version}
depend: [NobilityRegions, NobilityItems]
api-version: 1.14
commands:
   nobility:
      description: nobility
      usage: /nobility <argument> [other stuff]
      aliases: [ n ]
   estate:
     description: Nobility's Estate-related commands.
     usage: /estate <args> [other]
   test:
      description: Tests stuff
   create:
      description: Creates an estate at player's feet
      usage: /create or /c
      aliases: [ c ]
   blueprints:
      description: (DEBUG) Commands related to blueprints
      usage: /blueprints (argument) [other]
   nobility promote:
     description: Promotes a player on a nobility group.
     usage: /nobility promote <player>
     aliases:
       - /n promote
   nobility demote:
     description: Demotes a player on a nobility group.
     usage: /nobility demote <player>
     aliases:
       - /n demote
